### ISSUE TITLE
Alfred says : " Error in...

### ISSUE THREAD

**Issue by plphlpp** [giovannicoppola/alfred-fakeum#3]
#### ... module 'Fakeum' – no module named 'six.moves' "
hi
just fyi
this text is showing up in Alfred's window when typing the last letter of 'fake'.
this message covers Alfred's command 'Generate Fake Data - fake data for testing', which then disappears.
did a little debugging, found some things in ##### /libs/six.py
starting
line 164
```
class _SixMetaPathImporter(object):

    """
    A meta path importer to import six.moves and its submodules.

    This class implements a PEP302 finder and loader. It should be compatible
    with Python 2.5 and all existing versions of Python3
    """
```
following
line 209
```
def is_package(self, fullname):
    """
    Return true, if the named module is a package.

    We need this method to get correct spec objects with
    Python 3.4 (see PEP451)
    """
```
etc
stopped looking any further.
i'm on python 3.12.1.
and with Alfred 5.1.4
and took your latest release :
https://github.com/giovannicoppola/alfred-fakeum/releases/tag/v2.3.1

<img width="1065" alt="Bildschirmfoto 2024-02-08 um 21 43 19" src="https://github.com/giovannicoppola/alfred-fakeum/assets/73115227/e4d1bf0b-2100-4310-aec6-ac83d64b07f9">

<img width="1061" alt="Bildschirmfoto 2024-02-08 um 21 43 44" src="https://github.com/giovannicoppola/alfred-fakeum/assets/73115227/7f7e506f-b700-4230-9e6a-ad3b04ccbeec">

kind regards
all the best

**Comment by giovannicoppola** [comment]
thanks for the report @plphlpp. 
It is still working fine for me (but I am on 3.10.9). 
Could you check the debugger output?

**Comment by plphlpp** [comment]
> thanks for the report @plphlpp. 
> 
> It is still working fine for me (but I am on 3.10.9). 
> 
> Could you check the debugger output? 

debugger output : " Error in module 'Fakeum' – no module named 'six.moves' "

and much more

**Comment by anhkhoakz** [comment]
Here is the debugger output in my side @giovannicoppola :

```
[21:03:05.676] Logging Started...
[21:03:07.246] Fakeum[Script Filter] Queuing argument ''
[21:03:07.360] Fakeum[Script Filter] Script with argv '' finished
[21:03:07.363] ERROR: Fakeum[Script Filter] Code 1: .
21:03:07 workflow.py:2093 DEBUG    ---------- Fakeum (2.3.1) ----------
21:03:07 fakeum.py:228 DEBUG    query=''
21:03:07 workflow.py:2114 ERROR    No module named 'six.moves'
Traceback (most recent call last):
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/workflow/workflow.py", line 2107, in run
    func(self)
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/fakeum.py", line 258, in main
    fake_data = get_fake_data()
                ^^^^^^^^^^^^^^^
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/fakeum.py", line 197, in get_fake_data
    names = [n for n in names if supported_type(n)]
                                 ^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/fakeum.py", line 182, in supported_type
    for faker in all_fakers():
                 ^^^^^^^^^^^^
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/fakeum.py", line 132, in all_fakers
    from faker import Factory
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/__init__.py", line 2, in <module>
    from faker.factory import Factory  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/factory.py", line 13, in <module>
    from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/config.py", line 14, in <module>
    AVAILABLE_LOCALES = find_available_locales(PROVIDERS)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/utils/loading.py", line 44, in find_available_locales
    provider_module = import_module(provider_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/providers/address/__init__.py", line 5, in <module>
    from .. import date_time
  File "//Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/faker/providers/date_time/__init__.py", line 12, in <module>
    from dateutil.tz import tzlocal, tzutc
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.968A2AE3-3797-4E29-A803-71C67B6A7A11/libs/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
ModuleNotFoundError: No module named 'six.moves'
21:03:07 workflow.py:2116 INFO     for assistance, see: https://github.com/giovannicoppola/alfred-fakeum/issues
21:03:07 workflow.py:2136 DEBUG    ---------- finished in 0.034s ----------
[21:03:07.364] Fakeum[Script Filter] {
  "items": [
    {
      "title": "Error in workflow 'Fakeum'",
      "subtitle": "No module named 'six.moves'",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by giovannicoppola** [comment]
@anhkhoakz  @plphlpp do you have other pythons installed? 
(check  with `which -a python3`)

**Comment by anhkhoakz** [comment]
Yes, I've installed python and currently use pyenv as default

<img width="1377" alt="image" src="https://github.com/giovannicoppola/alfred-fakeum/assets/113995598/1d04d5ff-30ab-44b4-b786-450603d77736">

**Comment by giovannicoppola** [comment]
great, so to be able to use `alfred-fakeum` you will need to specify the complete path to the system python, as below
<img width="444" alt="image" src="https://github.com/giovannicoppola/alfred-fakeum/assets/5774411/12ab881e-d90b-45b5-be3d-e657b49060f4">

**Comment by anhkhoakz** [comment]
<img width="806" alt="image" src="https://github.com/giovannicoppola/alfred-fakeum/assets/113995598/e6b0f967-cc91-41e6-af1f-2d78f8b4c4b7">

I've changed it, but it's still had error.

**Comment by giovannicoppola** [comment]
you changed to homebrew, you need to change to system python

**Comment by anhkhoakz** [comment]
<img width="806" alt="image" src="https://github.com/giovannicoppola/alfred-fakeum/assets/113995598/ec19a6ee-63ec-49b3-9a5e-ec3671403ef4">

I've also changed to the pyenv, but it's still had the error

**Comment by giovannicoppola** [comment]
@anhkhoakz  you need to change it to the *system* python, please check the screenshot I sent

**Comment by anhkhoakz** [comment]
Oh, yes, thank you very much, it fixed the problem.

**Comment by Ronniexia** [comment]
Done! Thank you very much~

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “Alfred says : " Error in...”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
